spring:
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spider?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=UTC
    username: test
    password: zxc123!@#
#log配置
logging:
  file: jerryWebSpider.log
  root: info
  level.com.hytchare.jerrywebspider: DEBUG
  level.org.springframework.web: INFO
  level.org.hibernate: ERROR
#Tuwan地址
tuwan:
  #tuwan爬虫入口
  welfareUrl: https://api.tuwan.com/apps/Welfare/detail
  #图包存储路径
  #imageStorePath: /home/jerrySpider/tuwan
  imageStorePath: D:\Car\图包\全年龄\兔玩君分享计划
  spiderTaskName: tuwanSpiderTask
  downloadTaskName: tuwanDownloadTask
  album:
    welfareUrl: https://api.tuwan.com/apps/Welfare/detail
    spiderTaskName: tuwanAlbumSpiderTask
    downloadTaskName: tuwanAlbumDownloadTask
    imageStorePath: D:\Car\图包\全年龄\兔玩君分享计划
#Leshe地址
leshe:
  #leshe爬虫入口
  welfareUrl: http://111.231.221.217:34567/A:/
  #leshe待爬取相册大类，以英文逗号分隔
  collectionName: 喵写真,少女秩序,风之领域,轻兰映画,森罗财团
  #imageStorePath: /home/jerrySpider/leshe
  imageStorePath: D:\Car\图包\全年龄\乐摄
  spiderTaskName: lesheSpiderTask
  downloadTaskName: lesheDownloadTask
  album:
    #leshealbum爬虫入口
    welfareUrl: https://www.leshe.us/page/1
    #imageStorePath: /home/jerrySpider/leshe/album
    imageStorePath: D:\Car\图包\全年龄\乐摄
    spiderTaskName: lesheAlbumSpiderTask
    downloadTaskName: lesheAlbumDownloadTask
#服务端口
server:
  port: 8088
